# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.box = "ubuntu/wily64"
  config.vm.synced_folder "shared/", "/vagrant"
  config.vm.synced_folder "tmp/", "/tmpdir"
  config.vm.define "valhalla" do |valhalla|
  end

  config.vm.provision "shell", path: "jdk-build-requirements-provision"
end
